import { InvoiceData, DocumentHistoryItem, SubscriptionUsage } from "@/types";

export const sampleInvoice: InvoiceData = {
  id: "inv-2026-0841",
  fileName: "Apex_Cloud_Invoice_AUG2026.pdf",
  fileSize: "1.4 MB",
  pageCount: 1,
  uploadedAt: "2026-09-13 16:40",
  vendorName: "Apex Cloud Infrastructure Ltd.",
  vendorVatId: "EG-304-981-220",
  invoiceNumber: "INV-2026-9810",
  invoiceDate: "2026-09-01",
  dueDate: "2026-09-30",
  currency: "USD",
  subtotal: 5200.0,
  vatRate: 0.14,
  vatTotal: 728.0,
  totalAmount: 5928.0,
  overallConfidence: 0.93,
  mathAuditPassed: true,
  headerBoundingBoxes: {
    vendorName: { page: 1, x: 8, y: 7, width: 38, height: 5, label: "Vendor Name" },
    invoiceNumber: { page: 1, x: 62, y: 7, width: 30, height: 4, label: "Invoice Number" },
    invoiceDate: { page: 1, x: 62, y: 12.5, width: 30, height: 4, label: "Invoice Date" },
    dueDate: { page: 1, x: 62, y: 17.5, width: 30, height: 4, label: "Due Date" },
    vatTotal: { page: 1, x: 60, y: 76, width: 32, height: 4, label: "VAT 14%" },
    totalAmount: { page: 1, x: 60, y: 81.5, width: 32, height: 5, label: "Total Amount" },
  },
  lineItems: [
    {
      id: "li-1",
      itemDescription: "Enterprise Cloud Virtual Clusters (12-Mo License)",
      quantity: 1,
      unitPrice: 2400.0,
      taxRate: 0.14,
      taxAmount: 336.0,
      total: 2736.0,
      confidenceScores: {
        itemDescription: 0.98,
        quantity: 0.99,
        unitPrice: 0.97,
        taxRate: 0.99,
        total: 0.98,
      },
      boundingBoxes: {
        itemDescription: { page: 1, x: 8, y: 41, width: 44, height: 4.5, label: "Description: Item 1" },
        quantity: { page: 1, x: 53, y: 41, width: 8, height: 4.5, label: "Qty: Item 1" },
        unitPrice: { page: 1, x: 62, y: 41, width: 14, height: 4.5, label: "Price: Item 1" },
        taxRate: { page: 1, x: 77, y: 41, width: 8, height: 4.5, label: "VAT: Item 1" },
        total: { page: 1, x: 85, y: 41, width: 10, height: 4.5, label: "Total: Item 1" },
      },
    },
    {
      id: "li-2",
      itemDescription: "Kubernetes Load Balancing & Ingress Gateways",
      quantity: 2,
      unitPrice: 850.0,
      taxRate: 0.14,
      taxAmount: 238.0,
      total: 1938.0,
      confidenceScores: {
        itemDescription: 0.96,
        quantity: 0.98,
        unitPrice: 0.95,
        taxRate: 0.99,
        total: 0.96,
      },
      boundingBoxes: {
        itemDescription: { page: 1, x: 8, y: 47, width: 44, height: 4.5, label: "Description: Item 2" },
        quantity: { page: 1, x: 53, y: 47, width: 8, height: 4.5, label: "Qty: Item 2" },
        unitPrice: { page: 1, x: 62, y: 47, width: 14, height: 4.5, label: "Price: Item 2" },
        taxRate: { page: 1, x: 77, y: 47, width: 8, height: 4.5, label: "VAT: Item 2" },
        total: { page: 1, x: 85, y: 47, width: 10, height: 4.5, label: "Total: Item 2" },
      },
    },
    {
      id: "li-3",
      itemDescription: "Encrypted Multi-Region Object Storage (Overage 5TB)",
      quantity: 5,
      unitPrice: 120.0,
      taxRate: 0.14,
      taxAmount: 84.0,
      total: 684.0,
      confidenceScores: {
        itemDescription: 0.92,
        quantity: 0.94,
        unitPrice: 0.74, // LOW CONFIDENCE WARNING (< 0.85)
        taxRate: 0.99,
        total: 0.79, // LOW CONFIDENCE WARNING (< 0.85)
      },
      boundingBoxes: {
        itemDescription: { page: 1, x: 8, y: 53, width: 44, height: 4.5, label: "Description: Item 3" },
        quantity: { page: 1, x: 53, y: 53, width: 8, height: 4.5, label: "Qty: Item 3" },
        unitPrice: { page: 1, x: 62, y: 53, width: 14, height: 4.5, label: "Price: Item 3 (Low OCR 74%)" },
        taxRate: { page: 1, x: 77, y: 53, width: 8, height: 4.5, label: "VAT: Item 3" },
        total: { page: 1, x: 85, y: 53, width: 10, height: 4.5, label: "Total: Item 3 (Low OCR 79%)" },
      },
    },
    {
      id: "li-4",
      itemDescription: "24/7 Dedicated Financial SLA & Security Support",
      quantity: 1,
      unitPrice: 500.0,
      taxRate: 0.14,
      taxAmount: 70.0,
      total: 570.0,
      confidenceScores: {
        itemDescription: 0.97,
        quantity: 0.99,
        unitPrice: 0.98,
        taxRate: 0.99,
        total: 0.97,
      },
      boundingBoxes: {
        itemDescription: { page: 1, x: 8, y: 59, width: 44, height: 4.5, label: "Description: Item 4" },
        quantity: { page: 1, x: 53, y: 59, width: 8, height: 4.5, label: "Qty: Item 4" },
        unitPrice: { page: 1, x: 62, y: 59, width: 14, height: 4.5, label: "Price: Item 4" },
        taxRate: { page: 1, x: 77, y: 59, width: 8, height: 4.5, label: "VAT: Item 4" },
        total: { page: 1, x: 85, y: 59, width: 10, height: 4.5, label: "Total: Item 4" },
      },
    },
  ],
};

export const sampleHistoryDocuments: DocumentHistoryItem[] = [
  {
    id: "doc-001",
    fileName: "Apex_Cloud_Invoice_AUG2026.pdf",
    fileSize: "1.4 MB",
    vendorName: "Apex Cloud Infrastructure Ltd.",
    invoiceNumber: "INV-2026-9810",
    invoiceDate: "2026-09-01",
    totalAmount: 5928.0,
    currency: "USD",
    status: "verified",
    confidenceScore: 0.93,
    lineItemCount: 4,
  },
  {
    id: "doc-002",
    fileName: "Amazon_AWS_Statement_JUL2026.pdf",
    fileSize: "2.8 MB",
    vendorName: "Amazon Web Services Inc.",
    invoiceNumber: "AWS-39481029",
    invoiceDate: "2026-08-03",
    totalAmount: 14210.5,
    currency: "USD",
    status: "verified",
    confidenceScore: 0.98,
    lineItemCount: 18,
  },
  {
    id: "doc-003",
    fileName: "Cairo_Tech_Supplies_TaxInv_341.pdf",
    fileSize: "890 KB",
    vendorName: "شركة القاهرة للتوريدات التقنية",
    invoiceNumber: "TAX-EG-8491",
    invoiceDate: "2026-08-25",
    totalAmount: 84300.0,
    currency: "EGP",
    status: "warning", // Math or OCR discrepancy detected
    confidenceScore: 0.81,
    lineItemCount: 6,
  },
  {
    id: "doc-004",
    fileName: "Deloitte_Financial_Consulting_Q2.pdf",
    fileSize: "3.2 MB",
    vendorName: "Deloitte Middle East Services",
    invoiceNumber: "DEL-ME-2026-04",
    invoiceDate: "2026-07-15",
    totalAmount: 38000.0,
    currency: "USD",
    status: "verified",
    confidenceScore: 0.99,
    lineItemCount: 3,
  },
  {
    id: "doc-005",
    fileName: "Stripe_Processing_Statement_JUN2026.pdf",
    fileSize: "1.1 MB",
    vendorName: "Stripe Payments Europe Ltd.",
    invoiceNumber: "STR-002941",
    invoiceDate: "2026-07-01",
    totalAmount: 2150.8,
    currency: "USD",
    status: "verified",
    confidenceScore: 0.97,
    lineItemCount: 5,
  },
];

export const sampleSubscriptionUsage: SubscriptionUsage = {
  planName: "Individual Accountant",
  invoicesUsed: 45,
  monthlyLimit: 100,
  periodEnd: "October 1, 2026",
  batchUploadAvailable: true,
};
